version: '3.5'
services:
  ldap-account-manager:
    image: ghcr.io/ldapaccountmanager/lam:8.4
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - lamconfig:/var/lib/ldap-account-manager/config
    environment:
      - LAM_PASSWORD=${LAM_PASSWORD}
      - LAM_LANG=es_AR
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN}
    hostname: ldap-account-manager
  ldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    ports:
      - "389:389"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}

    command: "--loglevel info --copy-service"
    volumes:
      - ldap:/var/lib/ldap
      - slapd:/etc/ldap/slapd.d
    hostname: ldap

volumes:
  lamconfig:
  ldap:
  slapd: